# Generated by Django 3.1 on 2020-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_Pizza',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Desciption', models.TextField()),
                ('Size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Square_Pizza',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Desciption', models.TextField()),
                ('Size', models.CharField(max_length=10)),
            ],
        ),
    ]
