# Generated by Django 3.1 on 2020-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_pizza',
            name='Image',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='square_pizza',
            name='Image',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
