# Generated by Django 3.1 on 2020-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaAPP', '0002_auto_20201124_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=200)),
                ('Desciption', models.TextField()),
                ('Size', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Regular_Pizza',
        ),
        migrations.DeleteModel(
            name='Square_Pizza',
        ),
    ]
